services:
  n8n:
    image: n8nio/n8n:2.1.5
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
    ports:
      - "5678:5678"

  task-runners:
    build: ./runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-with-libraries:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
    depends_on:
      - n8n
